name: Book Library API CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  automation-test-job:
    runs-on: ubuntu-latest

    # Запуск Docker-контейнера PostgreSQL у хмарі GitHub Actions
    services:
      postgres-service:
        image: postgres:17
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: library_test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Clone repository resource layer
        uses: actions/checkout@v4

      - name: Initialize Python environment environment
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install compiled requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Execute pytest verification script
        run: pytest -v
        # Передаємо змінні середовища для підключення нашого conftest.py
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
          POSTGRES_DB: library_test_db
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: secret